#!/usr/bin/env bash
# Copyright 2026 Cloud-Dog, Viewdeck Engineering Limited
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -euo pipefail

MODE="${1:-${CHAT_CLIENT_MODE:-api}}"
ENV_FILE="${CHAT_CLIENT_ENV_FILE:-/app/env-docker-defaults}"
API_HOST="${CLOUD_DOG__API_SERVER__HOST:-${CHAT_CLIENT_API_HOST:-0.0.0.0}}"
API_PORT="${CLOUD_DOG__API_SERVER__PORT:-${CHAT_CLIENT_API_PORT:-0}}"
WEB_PORT="${CLOUD_DOG__WEB_SERVER__PORT:-${CHAT_CLIENT_WEB_PORT:-0}}"
MCP_PORT="${CLOUD_DOG__MCP_SERVER__PORT:-${CHAT_CLIENT_MCP_PORT:-0}}"
A2A_PORT="${CLOUD_DOG__A2A_SERVER__PORT:-${CHAT_CLIENT_A2A_PORT:-0}}"
APP_USER="$(id -un)"
APP_HOME="${HOME:-/home/${APP_USER}}"

print_banner() {
  echo "============================================================"
  echo "cloud-dog-chat-client container"
  echo "============================================================"
  echo "Mode: ${MODE}"
  echo "Env file: ${ENV_FILE}"
  echo "API bind: ${API_HOST}:${API_PORT}"
  echo "Web bind: 0.0.0.0:${WEB_PORT}"
  echo "MCP bind: 0.0.0.0:${MCP_PORT}"
  echo "A2A bind: 0.0.0.0:${A2A_PORT}"
  echo "Run user: ${APP_USER}"
  echo "============================================================"
}

setup_shell_runtime() {
  local runtime_env_file="/app/chat-client-runtime-env.sh"
  {
    echo "#!/usr/bin/env bash"
    echo "# generated by docker-entrypoint.chat-client.sh"
    while IFS='=' read -r key value; do
      printf 'export %s=%q\n' "$key" "$value"
    done < <(env | grep -E '^(CLOUD_DOG__|CHAT_CLIENT_)')
  } > "${runtime_env_file}"
  chmod 0644 "${runtime_env_file}"

  local bash_profile="${APP_HOME}/.bash_profile"
  local marker="# cloud-dog-chat-client:auto-chat"
  if [[ ! -f "${bash_profile}" ]] || ! grep -q "${marker}" "${bash_profile}"; then
    cat >> "${bash_profile}" <<'PROFILE_EOF'
# cloud-dog-chat-client:auto-chat
if [[ -f /app/chat-client-runtime-env.sh ]]; then
  source /app/chat-client-runtime-env.sh
fi
if [[ -n "${SSH_TTY:-}" ]] && command -v cloud-dog-chat >/dev/null 2>&1; then
  export CLOUD_DOG__APP__ENV_FILE="${CHAT_CLIENT_ENV_FILE:-/app/env-docker-defaults}"
  export CLOUD_DOG__APP__PROJECT_ROOT="${CLOUD_DOG__APP__PROJECT_ROOT:-/app}"
  export CLOUD_DOG__APP__LOGFOLDER="${CHAT_CLIENT_LOGFOLDER:-/tmp/chat-client-logs}"
  mkdir -p "${CLOUD_DOG__APP__LOGFOLDER}"
  printf 'Press ? for help\n'
  exec cloud-dog-chat chat --no-rich
fi
PROFILE_EOF
  fi
}

run_migration_preflight() {
  echo "Running database migration preflight..."
python3 - <<'PY'
import os
from pathlib import Path
import sys

sys.path.insert(0, str(Path("/app/src")))

from cloud_dog_chat_client.config import ConfigManager
from cloud_dog_chat_client.database.runtime import ChatDatabaseRuntime

cfg = ConfigManager(env_file=os.environ.get("CHAT_CLIENT_ENV_FILE") or "/app/env-docker-defaults")
runtime = ChatDatabaseRuntime(cfg)
runtime.dispose()
print("Database migration preflight complete")
PY
}

wait_for_surface() {
  local pid="$1"
  local port="$2"
  local label="$3"
  local attempt

  for attempt in $(seq 1 60); do
    if ! kill -0 "${pid}" 2>/dev/null; then
      local child_status
      if wait "${pid}"; then
        child_status=0
      else
        child_status=$?
      fi
      echo "${label} exited before binding port ${port} (status ${child_status})" >&2
      return "${child_status}"
    fi
    # Bash builtin /dev/tcp probe — the runtime base image does not ship nc/netcat,
    # so nc -z always failed and the surface was declared un-bound despite serving
    # traffic (W28R-3023: readiness must not depend on an absent external tool).
    if (exec 3<>"/dev/tcp/127.0.0.1/${port}") >/dev/null 2>&1; then
      echo "${label} ready on port ${port}"
      return 0
    fi
    sleep 1
  done

  echo "${label} did not bind port ${port} within 60 seconds" >&2
  return 124
}

start_surface() {
  local script="$1"
  local port="$2"
  local label="$3"

  python3 "${script}" &
  local pid=$!
  pids+=("${pid}")
  wait_for_surface "${pid}" "${port}" "${label}"
}

print_banner
setup_shell_runtime

export CLOUD_DOG__APP__PROJECT_ROOT="${CLOUD_DOG__APP__PROJECT_ROOT:-/app}"
export CLOUD_DOG__APP__ENV_FILE="${ENV_FILE}"
export CLOUD_DOG__API_SERVER__HOST="${API_HOST}"
export CLOUD_DOG__API_SERVER__PORT="${API_PORT}"
export CLOUD_DOG__API_SERVER__BASE_URL="${CLOUD_DOG__API_SERVER__BASE_URL:-http://127.0.0.1:${API_PORT}}"
export CLOUD_DOG__API_SERVER__HOST="${CLOUD_DOG__API_SERVER__HOST:-${API_HOST}}"
export CLOUD_DOG__API_SERVER__PORT="${CLOUD_DOG__API_SERVER__PORT:-${API_PORT}}"
export CLOUD_DOG__WEB_SERVER__HOST="${CLOUD_DOG__WEB_SERVER__HOST:-0.0.0.0}"
export CLOUD_DOG__WEB_SERVER__PORT="${CLOUD_DOG__WEB_SERVER__PORT:-${WEB_PORT}}"
export CLOUD_DOG__MCP_SERVER__HOST="${CLOUD_DOG__MCP_SERVER__HOST:-0.0.0.0}"
export CLOUD_DOG__MCP_SERVER__PORT="${CLOUD_DOG__MCP_SERVER__PORT:-${MCP_PORT}}"
export CLOUD_DOG__A2A_SERVER__HOST="${CLOUD_DOG__A2A_SERVER__HOST:-0.0.0.0}"
export CLOUD_DOG__A2A_SERVER__PORT="${CLOUD_DOG__A2A_SERVER__PORT:-${A2A_PORT}}"

case "${MODE}" in
  all)
    run_migration_preflight
    pids=()
    terminate_children() {
      for pid in "${pids[@]:-}"; do
        kill "${pid}" 2>/dev/null || true
      done
      wait || true
    }
    trap terminate_children EXIT INT TERM

    # Each server constructs the shared database runtime during import.  Start
    # surfaces one at a time so a fresh SQLite database cannot be seeded by four
    # writers concurrently.  Once a port is listening, that surface has finished
    # its migration/seed path and the next surface can safely initialise.
    start_surface /app/start_api_server.py "${API_PORT}" "API server"
    start_surface /app/start_web_server.py "${WEB_PORT}" "Web server"
    start_surface /app/start_mcp_server.py "${MCP_PORT}" "MCP server"
    start_surface /app/start_a2a_server.py "${A2A_PORT}" "A2A server"
    wait -n "${pids[@]}"
    exit $?
    ;;
  api|server|test-server)
    run_migration_preflight
    exec python3 /app/start_api_server.py
    ;;
  web)
    exec python3 /app/start_web_server.py
    ;;
  mcp)
    run_migration_preflight
    exec python3 /app/start_mcp_server.py
    ;;
  a2a)
    run_migration_preflight
    exec python3 /app/start_a2a_server.py
    ;;
  chat)
    exec cloud-dog-chat chat --no-rich
    ;;
  status)
    exec /app/server_control.sh --env "${ENV_FILE}" status all
    ;;
  shell|bash)
    exec /bin/bash
    ;;
  *)
    exec "$@"
    ;;
esac
